import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { NavMenuProvider } from "@/context/NavMenuContext";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fluentica.md",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} h-full antialiased`}
    >
      <body>
        <NavMenuProvider>
          <Navbar />
          {children}
          <Footer />
        </NavMenuProvider>
      </body>
    </html>
  );
}
